### ISSUE TITLE
关于GitHubGit

### ISSUE THREAD

**Issue by wangdaodao** [weakish/plugins#10]
typecho是开发最新版，不知道现在插件还支持吗？

setup GitHub web hook这里，关于action url，没有看明白，能详细的说下吗？

**Comment by weakish** [comment]
不知道，我这两年不用 typecho 了

> 关于action url，没有看明白

没看明白是对的，因为这里的做法完全是违反逻辑的。这里

```
http://typecho.example.com/action/curtseyingpiddlesMiguelyeshivahsclarinettists
```

的 `curtseyingpiddlesMiguelyeshivahsclarinettists`

对应 `Plugin.php` 中的 `const github_git = 'curtseyingpiddlesMiguelyeshivahsclarinettists'    ;`

也就是说：

1. 没有提供修改配置的 UI，通过直接修改源代码的方式进行配置
2. 通过复杂的 url 来实现「认证」的效果，十分 naive，而且 http 下还有严重的安全缺陷

综上，如果你有这个需求，建议你重新写一个插件

**Comment by wangdaodao** [comment]
> 不知道，我这两年不用 typecho 了
> 
> > 关于action url，没有看明白
> 
> 没看明白是对的，因为这里的做法完全是违反逻辑的。这里
> 
> ```
> http://typecho.example.com/action/curtseyingpiddlesMiguelyeshivahsclarinettists
> ```
> 的 `curtseyingpiddlesMiguelyeshivahsclarinettists`
> 
> 对应 `Plugin.php` 中的 `const github_git = 'curtseyingpiddlesMiguelyeshivahsclarinettists' ;`
> 
> 也就是说：
> 
> 1. 没有提供修改配置的 UI，通过直接修改源代码的方式进行配置
> 2. 通过复杂的 url 来实现「认证」的效果，十分 naive，而且 http 下还有严重的安全缺陷
> 
> 综上，如果你有这个需求，建议你重新写一个插件

好的，谢谢
